---

- name: Base Settings
  include: copy_file.yml


- name: Install MySQL 
  include: install_MySQL.yml 

- name: Master-slave replication
  include: rep_MySQL.yml

- name: install keepalived
  include: install_keepalived.yml
